---
title: "WEB PAGE BABY"
date: 2021-09-28
---
theme: minima
title: My webpage
author: Jason
email: Jason@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello dddffeffefefef
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
